install:
	npm ci

start:
	npm start

build: .force_build
	npm run build

.force_build:
	touch .force_build

test:
	npm test

eject:
	npm eject

lint:
	npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.json . --fix
